server:
  port: 8080
  servlet:
    contextPath: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}/haruhanal?createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 20
      pool-name: haruhanal-user-pool

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/haruhanal?createDatabaseIfNotExist=true
#    username: root
#    password: 1234
#    hikari:
#      auto-commit: false
#      connection-test-query: SELECT 1
#      minimum-idle: 10
#      maximum-pool-size: 20
#      pool-name: haruhanal-user-pool

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: create
    open-in-view: false
    show-sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    static-path-pattern: /static/**

logging.level:
  org.hibernate.SQL: debug

management:
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: prometheus

#springdoc:
#  swagger-ui:
#    # swagger-ui 접근 경로. default 값은 /swagger-ui.html이다.
#    path: /swagger-custom-ui.html
#
#    # 각 API의 그룹 표시 순서
#    # path, query, body, response 순으로 출력
#    groups-order: DESC
#
#    # 태그 정렬 순서.
#    # alpha: 알파벳 순 정렬
#    # method: OpenAPI specification file에 원하는 태그 정렬 방식 직접 기재
#    tags-sorter: alpha
#
#    # 컨트롤러 정렬 순서.
#    # method는 delete - get - patch - post - put 순으로 정렬된다.
#    # alpha를 사용해 알파벳 순으로 정렬할 수 있다.
#    operations-sorter: method
#
#    # swagger-ui default url인 petstore html의 비활성화 설정
#    disable-swagger-default-url: true
#
#    # swagger-ui에서 try 했을 때 request duration을 알려주는 설정
#    display-request-duration: true
#
#  # openAPI 접근 경로. default 값은 /v3/api-docs 이다.
#  api-docs:
#    path: /api-docs
#
#  # Spring Actuator의 endpoint까지 보여줄 것인지?
#  show-actuator: true
#
#  # request media type 의 기본 값
#  default-consumes-media-type: application/json
#
#  # response media type 의 기본 값
#  default-produces-media-type: application/json
#
#  # 해당 패턴에 매칭되는 controller만 swagger-ui에 노출한다.
#  paths-to-match:
#    - /api/**

aws:
  s3:
    credentials:
      access-key: test
      secret-key: test
    region:
      static: test
    bucket: test